<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email_kosong</name>
   <tag></tag>
   <elementGuidId>b15d20f7-5fca-450b-a847-e5fef071aace</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#authentication-input-error_cf0fc47a-6260-45e5-9bdb-a1ac8ede14d8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='authentication-input-error_cf0fc47a-6260-45e5-9bdb-a1ac8ede14d8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fdab64e9-052a-4973-a396-b6e6d1e29e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>authentication-input-error_cf0fc47a-6260-45e5-9bdb-a1ac8ede14d8</value>
      <webElementGuid>0fb373d5-4da5-4e1b-b17b-61db284e04eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pYVjxt</value>
      <webElementGuid>a8cb4fb6-4a5a-4821-953a-c78de6b03ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>e3677472-c35c-4d71-93b8-6b503cd6910a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mohon isi di kolom berikut</value>
      <webElementGuid>21de16d6-6bc0-4c88-ad99-0eac138c3aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authentication-input-error_cf0fc47a-6260-45e5-9bdb-a1ac8ede14d8&quot;)</value>
      <webElementGuid>eb2c3bc4-5833-450a-a1a0-708f6e84ea04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='authentication-input-error_cf0fc47a-6260-45e5-9bdb-a1ac8ede14d8']</value>
      <webElementGuid>6eedad11-1b50-4ce2-a106-e5c995cec82a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/div/div[2]/form/div/div[2]/div[2]/div[2]</value>
      <webElementGuid>bba7b505-2e48-44c6-9002-2ddee206791f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akun dan/atau password Anda salah, silakan coba lagi'])[1]/following::div[3]</value>
      <webElementGuid>0b934033-87a8-40a0-a253-be62971ad713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in dengan QR'])[1]/following::div[8]</value>
      <webElementGuid>939fa9ef-9a6f-4c01-99a2-7a6455cca165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[3]/preceding::div[4]</value>
      <webElementGuid>7ea93d61-0b51-479b-a5f1-49c35783861c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Password'])[1]/preceding::div[4]</value>
      <webElementGuid>f1ccbd95-d13e-4f9b-bdde-d7d151aacc8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mohon isi di kolom berikut']/parent::*</value>
      <webElementGuid>6785052d-af68-48ad-b559-96507ab656e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]</value>
      <webElementGuid>68308a48-5756-4b84-a251-6d911bfdd342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'authentication-input-error_cf0fc47a-6260-45e5-9bdb-a1ac8ede14d8' and (text() = 'Mohon isi di kolom berikut' or . = 'Mohon isi di kolom berikut')]</value>
      <webElementGuid>2ad4adea-fa08-49fb-844e-b7c7ed47abde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
