<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email_invalid</name>
   <tag></tag>
   <elementGuidId>256546d0-4747-4b18-b803-37a74d1368ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.gCY-Ye</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div/div/div/div[2]/form/div/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9492b4f5-b694-424e-81f3-35fc50f3fd9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gCY-Ye</value>
      <webElementGuid>a239c8b4-6980-422a-ae34-a34876f2de69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akun atau password yang dimasukkan salah. Silakan ganti password jika kamu mengalami kesulitan login.</value>
      <webElementGuid>2d68f978-f9bf-4952-989b-daeaed6aef2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;vtexOX&quot;]/div[1]/div[@class=&quot;_3M9lzn PeA8Gc&quot;]/div[@class=&quot;Gxi65y&quot;]/div[2]/form[1]/div[@class=&quot;IxqCyD J1i6cp B-fiUo&quot;]/div[@class=&quot;yXry6s&quot;]/div[@class=&quot;_8cXplf fu1xRy ek+JS+&quot;]/div[2]/div[@class=&quot;gCY-Ye&quot;]</value>
      <webElementGuid>80c83a47-3458-44a7-b36a-30989c7c90ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/div/div[2]/form/div/div[2]/div/div[2]/div</value>
      <webElementGuid>603b7c6d-0045-4d14-8720-574ecc2e9d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in dengan QR'])[1]/following::div[5]</value>
      <webElementGuid>c57bc0a3-7c93-494f-9747-ad2fa3f8d478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[2]/following::div[7]</value>
      <webElementGuid>b78d1898-59c3-4771-bbe0-61f155c0dd67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[3]/preceding::div[7]</value>
      <webElementGuid>5aaaa16f-8c37-4539-aa24-192e1d42ace6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Password'])[1]/preceding::div[7]</value>
      <webElementGuid>aca5d50e-fec9-4996-967f-134ea248c1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Akun atau password yang dimasukkan salah. Silakan ganti password jika kamu mengalami kesulitan login.']/parent::*</value>
      <webElementGuid>b4f49f6a-30aa-42de-bdfe-2d8e5f1af569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>4cab3cd2-8dbd-4c94-904d-0b4170785d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Akun atau password yang dimasukkan salah. Silakan ganti password jika kamu mengalami kesulitan login.' or . = 'Akun atau password yang dimasukkan salah. Silakan ganti password jika kamu mengalami kesulitan login.')]</value>
      <webElementGuid>bcb810e9-60aa-4916-951f-e164cf06d41c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
