<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>password_kosong</name>
   <tag></tag>
   <elementGuidId>e33d7c03-e090-47fd-82a6-f195efda7f4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#authentication-input-error_63213125-b977-48e1-bd11-14996fb83e04</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='authentication-input-error_63213125-b977-48e1-bd11-14996fb83e04']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c7174672-0b06-460d-89c8-ab7c520348db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>authentication-input-error_63213125-b977-48e1-bd11-14996fb83e04</value>
      <webElementGuid>6a5fca47-fe2b-4604-9976-10db00a7cea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pYVjxt</value>
      <webElementGuid>54cd4188-9671-44bf-822e-ecf876dfc76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>1925b574-0e60-4bdd-8888-2503cd21db51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mohon isi di kolom berikut</value>
      <webElementGuid>2542e739-4de8-4b9d-ab9d-22b468f2ba09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authentication-input-error_63213125-b977-48e1-bd11-14996fb83e04&quot;)</value>
      <webElementGuid>c66fa7ae-dfdc-4b56-abd1-e34e9a474db1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='authentication-input-error_63213125-b977-48e1-bd11-14996fb83e04']</value>
      <webElementGuid>ad24a5e6-fcbf-4b2a-8de3-66fa9cd4d81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/div/div[2]/form/div/div[2]/div[3]/div[2]</value>
      <webElementGuid>50bbde24-1211-4bd7-97cd-71f05b980735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mohon isi di kolom berikut'])[1]/following::div[3]</value>
      <webElementGuid>a5ded01c-aa12-4644-bc69-eb50cc9251fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in dengan QR'])[1]/following::div[8]</value>
      <webElementGuid>c93e66fa-d37a-40b8-a978-51b811b46b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[3]/preceding::div[1]</value>
      <webElementGuid>a69b81e3-8bd2-4f63-b212-75c11b8d1613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Password'])[1]/preceding::div[1]</value>
      <webElementGuid>b536d187-0e90-4c8f-b10d-d9f68876edea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]</value>
      <webElementGuid>f1e9b8be-a151-45ba-a0af-535f633aae75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'authentication-input-error_63213125-b977-48e1-bd11-14996fb83e04' and (text() = 'Mohon isi di kolom berikut' or . = 'Mohon isi di kolom berikut')]</value>
      <webElementGuid>a9aab3eb-a54e-40ea-a6e3-99d6117ead34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
