<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shopee-banner-popup-stateful</name>
   <tag></tag>
   <elementGuidId>8b70938d-1d5f-4d56-b7e5-f9559f64948d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>shopee-banner-popup-stateful</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div/div/shopee-banner-popup-stateful</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>shopee-banner-popup-stateful</value>
      <webElementGuid>514fa636-d8ba-4156-83d3-030eb3acbf2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spacekey</name>
      <type>Main</type>
      <value>PC-ID-HOME_POPUP_01</value>
      <webElementGuid>67345c94-a214-43de-8db0-fa12b7fcb1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[2]/div[@class=&quot;UFyQ8p N80rpt&quot;]/div[@class=&quot;home-page&quot;]/shopee-banner-popup-stateful[1]</value>
      <webElementGuid>4ea8e29f-a3af-4d11-8de8-702e191a3ae1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/shopee-banner-popup-stateful</value>
      <webElementGuid>3c661677-fb00-4090-adfa-6dcf8856abd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//shopee-banner-popup-stateful</value>
      <webElementGuid>a331bb8e-3c34-4667-ba3c-c3e0a515a070</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
