<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_home-popup__close-button-tateful-a61</name>
   <tag></tag>
   <elementGuidId>f2be3fb5-43f3-49ac-8473-3c766b95edf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.home-popup > div.home-popup__background > div.home-popup__content > div.home-popup__close-area > div.shopee-popup__close-btn > svg.home-popup__close-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>e5c69e36-52ac-45e1-82c3-95e611aa5175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 16 16</value>
      <webElementGuid>8d9e5880-9a78-4fb7-93cc-e942ddb02e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#EE4D2D</value>
      <webElementGuid>ab247ab9-fac6-4ef4-8fe6-d482ee7ca122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>home-popup__close-button</value>
      <webElementGuid>4e41ea65-e0e0-4d31-bf43-7cbce0f6820e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;home-popup&quot;]/div[@class=&quot;home-popup__background&quot;]/div[@class=&quot;home-popup__content&quot;]/div[@class=&quot;home-popup__close-area&quot;]/div[@class=&quot;shopee-popup__close-btn&quot;]/svg[@class=&quot;home-popup__close-button&quot;]</value>
      <webElementGuid>0fb927e4-94e2-43fa-a7b7-cc4381660f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Shopee Indonesia/shopee-banner-popup-stateful</value>
      <webElementGuid>863f4da0-3f96-4ea3-9bb8-484ee1e047da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bd7509ba-019f-4406-b5e7-309d11b9ca50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>88657928-7983-4d45-a7d4-3a62a122f46f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
