<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pakaian Wanita</name>
   <tag></tag>
   <elementGuidId>a5b4c4df-6ad4-4bd1-928c-33cb39babdd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div/div/div[3]/div[2]/div/div/div[2]/div/div/ul/li[8]/a/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fba0ff3b-ff0a-4f27-bd2a-f92df0d8cfd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_0qFceF</value>
      <webElementGuid>1d45b4e8-1d20-47c4-9e72-1e8cdbcd077d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pakaian Wanita</value>
      <webElementGuid>30431231-c86f-4e49-84c3-29da45a7f968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[2]/div[@class=&quot;UFyQ8p N80rpt&quot;]/div[@class=&quot;home-page&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;section-below-the-fold&quot;]/div[@class=&quot;home-category-list&quot;]/div[@class=&quot;shopee-header-section home-category-list__header shopee-header-section--simple&quot;]/div[@class=&quot;shopee-header-section__content&quot;]/div[@class=&quot;image-carousel&quot;]/div[@class=&quot;image-carousel__item-list-wrapper&quot;]/ul[@class=&quot;image-carousel__item-list&quot;]/li[@class=&quot;image-carousel__item&quot;]/a[@class=&quot;home-category-list__category-grid&quot;]/div[@class=&quot;g3RFjs&quot;]/div[@class=&quot;GE2Jnm&quot;]/div[@class=&quot;_0qFceF&quot;]</value>
      <webElementGuid>7888bf21-f659-4bb2-8029-08a044f670ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/div[3]/div[2]/div/div/div[2]/div/div/ul/li[8]/a/div/div[2]/div</value>
      <webElementGuid>32f4f112-94f9-48e2-ac9b-f3e6f3f7f408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pakaian Pria'])[1]/following::div[6]</value>
      <webElementGuid>db79ef6d-5ffc-499b-b1fb-862359364ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perlengkapan Rumah'])[1]/following::div[12]</value>
      <webElementGuid>682b93c3-212a-4d99-b804-3d07ef36ebd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sepatu Pria'])[1]/preceding::div[4]</value>
      <webElementGuid>b0a7f69e-e7d4-428f-aef2-4caa1091b0f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fashion Muslim'])[1]/preceding::div[10]</value>
      <webElementGuid>a3522e16-4cbe-43f7-a6a7-408f8a12d304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pakaian Wanita']/parent::*</value>
      <webElementGuid>9a72532c-663d-4b41-a784-063d01aab10e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a/div/div[2]/div</value>
      <webElementGuid>10dd07e0-f238-4bf7-9f9f-66e1db37c18f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pakaian Wanita' or . = 'Pakaian Wanita')]</value>
      <webElementGuid>8b116819-b092-40f7-b8f1-aa60d2e3787a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
