<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shopee-banner-popup-stateful</name>
   <tag></tag>
   <elementGuidId>2b51d159-0ecf-4f1a-911b-03e7c56f8141</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div/div/shopee-banner-popup-stateful</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>shopee-banner-popup-stateful</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>shopee-banner-popup-stateful</value>
      <webElementGuid>d4d5c078-7ba9-4a38-ac14-496994d184da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spacekey</name>
      <type>Main</type>
      <value>PC-ID-HOME_POPUP_01</value>
      <webElementGuid>1179f51c-8404-4bee-b8c3-9b25be6cf08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[2]/div[@class=&quot;UFyQ8p N80rpt&quot;]/div[@class=&quot;home-page&quot;]/shopee-banner-popup-stateful[1]</value>
      <webElementGuid>2e0c07f4-1725-4721-9364-2eed71d02940</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/shopee-banner-popup-stateful</value>
      <webElementGuid>01dd6d30-0011-44cc-9a19-20ca6033ff23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//shopee-banner-popup-stateful</value>
      <webElementGuid>04ce2232-eb11-4b39-ab9c-56e27b46fdf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
