<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_home-popup__close-button-tateful-862</name>
   <tag></tag>
   <elementGuidId>fa6acb4e-d288-4de9-9273-3df8f9ff6923</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.home-popup > div.home-popup__background > div.home-popup__content > div.home-popup__close-area > div.shopee-popup__close-btn > svg.home-popup__close-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>c36be80f-0878-4ee7-9574-b2b115baa2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 16 16</value>
      <webElementGuid>87c318c9-59da-4689-877e-e448a264be88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#EE4D2D</value>
      <webElementGuid>84171d5c-5849-4dfb-89c8-67a485b6b40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>home-popup__close-button</value>
      <webElementGuid>8f456496-4701-467c-9f32-c3d17b166ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div[@class=&quot;home-popup&quot;]/div[@class=&quot;home-popup__background&quot;]/div[@class=&quot;home-popup__content&quot;]/div[@class=&quot;home-popup__close-area&quot;]/div[@class=&quot;shopee-popup__close-btn&quot;]/svg[@class=&quot;home-popup__close-button&quot;]</value>
      <webElementGuid>29269973-142e-476e-a717-e5cb6ee44aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/search/Page_Shopee Indonesia  Situs Belanja Online_073d3b/shopee-banner-popup-stateful</value>
      <webElementGuid>5f5da3d1-be69-4af0-913d-fdd6c7a46c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0da05b02-b14d-45e0-9c84-15c29f15841d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>5c2c3c2d-2ddf-4050-8e3e-893522878eb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
