<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Log in dengan QR_loginKey</name>
   <tag></tag>
   <elementGuidId>a849a4ba-66cb-4cd7-9ec9-a15a63f94c51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;loginKey&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='loginKey']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b132d79-ce56-4799-b55b-644962c329c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pDzPRp</value>
      <webElementGuid>97183796-bb8e-4c01-8555-9d1982500cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2113efd-9362-40b3-a0f9-f21f44b7c423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No. Handphone/Username/Email</value>
      <webElementGuid>88238a81-15bc-419a-b353-72286a006c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>33bc14f7-af2c-4d05-8e24-2c077938dea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loginKey</value>
      <webElementGuid>a348f3a8-0c9e-45a2-bdd2-9bb3a642dc52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>0cd7ed6e-6771-43ec-913b-e17b5673829c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>515c1b45-2cb0-45af-bad2-83c999651413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;vtexOX&quot;]/div[1]/div[@class=&quot;_3M9lzn PeA8Gc&quot;]/div[@class=&quot;Gxi65y&quot;]/div[2]/form[1]/div[@class=&quot;IxqCyD J1i6cp B-fiUo&quot;]/div[@class=&quot;yXry6s&quot;]/div[@class=&quot;D3QIf1&quot;]/div[@class=&quot;yup5K8 SdUtrz&quot;]/input[@class=&quot;pDzPRp&quot;]</value>
      <webElementGuid>0d1beecf-ff7b-4a15-aa04-436ad8ff3d14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='loginKey']</value>
      <webElementGuid>4046b5e2-54c2-4088-9442-3616cca70dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/div/div[2]/form/div/div[2]/div[2]/div/input</value>
      <webElementGuid>acd80042-ffb7-4437-8892-ae39bbc91c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b3003080-6758-40fd-beda-862bfbcafc80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'No. Handphone/Username/Email' and @name = 'loginKey']</value>
      <webElementGuid>92d80e7e-a850-4a7f-b5e3-1f00d05d7366</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
