<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pakaian Wanita</name>
   <tag></tag>
   <elementGuidId>22925ff3-efdc-4191-b74d-55e056fb6b61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div/div/div[4]/div/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.shopee-category-list__main-category__link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a2515b49-efb2-4fcc-95ad-5e63654a2252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shopee-category-list__main-category__link</value>
      <webElementGuid>333db89d-4bd2-42b9-b230-974903ddb337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Pakaian-Wanita-cat.11042745</value>
      <webElementGuid>9d029a47-b22d-4fc3-8202-e67bc7b02cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pakaian Wanita</value>
      <webElementGuid>e2bfe79a-057c-4d6b-b690-032089210dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[2]/div[@class=&quot;KNvL88&quot;]/div[@class=&quot;vfEs0w&quot;]/div[@class=&quot;container cZOmU2&quot;]/div[@class=&quot;shopee-filter-panel&quot;]/div[@class=&quot;shopee-category-list&quot;]/div[@class=&quot;shopee-category-list__body&quot;]/div[@class=&quot;shopee-category-list__category&quot;]/div[@class=&quot;shopee-category-list__main-category shopee-category-list__main-category--active&quot;]/a[@class=&quot;shopee-category-list__main-category__link&quot;]</value>
      <webElementGuid>f2396326-1a29-4b98-a355-a243d880d1bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/div[4]/div/div/div/div/div/a</value>
      <webElementGuid>eac2bcb6-0f2b-43ed-a200-ff5202856d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pakaian Wanita')]</value>
      <webElementGuid>0bf8d12e-de74-41b2-897e-33660d2e1713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Kategori'])[1]/following::a[1]</value>
      <webElementGuid>172d5807-6bc9-4fb1-a053-45e5db244ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sleepwear'])[1]/following::a[2]</value>
      <webElementGuid>f6eaaa88-8949-44b3-92c0-d1d42da202b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pakaian Tradisional'])[1]/preceding::a[1]</value>
      <webElementGuid>7c159b14-15c3-4d53-a7a0-5645d71d5770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kostum'])[1]/preceding::a[2]</value>
      <webElementGuid>78674c9e-442c-4d00-83cd-d3496fd814a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pakaian Wanita']/parent::*</value>
      <webElementGuid>d02bd6b7-b039-442e-bf57-fca741721d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/Pakaian-Wanita-cat.11042745')])[2]</value>
      <webElementGuid>5f141702-5a6d-4754-a199-ce08ee1c52e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/a</value>
      <webElementGuid>84d3247d-a85b-4281-9036-79dbdc537d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Pakaian-Wanita-cat.11042745' and (text() = 'Pakaian Wanita' or . = 'Pakaian Wanita')]</value>
      <webElementGuid>fdb47a2e-8a28-44ee-af45-0f245ac83f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
