<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dress</name>
   <tag></tag>
   <elementGuidId>3f56c815-76d4-41ec-a29b-a02818a3f05a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div/div/div[3]/div/div[2]/div/div/ul/li[4]/div/div/a/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ee3d0fb9-5f25-4dde-8928-a3a1ac7844c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>collection-card__collection-title</value>
      <webElementGuid>ca9325e6-fb95-4a2a-b3d1-93c72e840a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dress</value>
      <webElementGuid>a3c96a2e-137a-48c6-aa77-42a48442da55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[2]/div[@class=&quot;KNvL88&quot;]/div[@class=&quot;vfEs0w&quot;]/div[@class=&quot;curated-collections container&quot;]/div[@class=&quot;shopee-header-section a-curated-collection-model shopee-header-section--simple&quot;]/div[@class=&quot;shopee-header-section__content&quot;]/div[@class=&quot;image-carousel&quot;]/div[@class=&quot;image-carousel__item-list-wrapper&quot;]/ul[@class=&quot;image-carousel__item-list&quot;]/li[@class=&quot;image-carousel__item&quot;]/div[@class=&quot;product-recommend-items__item-wrapper&quot;]/div[@class=&quot;collection-card&quot;]/a[@class=&quot;collection-card-link&quot;]/div[@class=&quot;collection-card__collection-title&quot;]</value>
      <webElementGuid>15a7afe1-2398-4a0e-a3c0-68917c2cad9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/div[3]/div/div[2]/div/div/ul/li[4]/div/div/a/div[2]</value>
      <webElementGuid>1e0c1b41-41af-4bf5-9653-e43ccb9c3aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outerwear'])[1]/following::div[6]</value>
      <webElementGuid>a4dc8585-9e7d-4cb3-9c39-042d33b61d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jeans'])[1]/following::div[12]</value>
      <webElementGuid>3fe8059d-3ecb-412d-a789-1e198e2f2394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pants'])[1]/preceding::div[4]</value>
      <webElementGuid>801589ed-e152-4e1b-8732-6ac0694f41ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skirts'])[1]/preceding::div[10]</value>
      <webElementGuid>88113db7-5d18-4f49-9d1f-ceb0e476c41c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dress']/parent::*</value>
      <webElementGuid>7155e859-422a-469b-8673-aff2bfe41f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div/a/div[2]</value>
      <webElementGuid>4396886a-fb59-404f-b884-5d6ef81e2713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Dress' or . = 'Dress')]</value>
      <webElementGuid>ac8f79b7-4a81-4a99-bfc4-ba92a0d3f038</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
