<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Log in dengan QR_loginKey</name>
   <tag></tag>
   <elementGuidId>281aaeac-792f-45e5-b75a-517e48448fb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='loginKey']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;loginKey&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3295ed5f-1894-4188-a0af-060d81c92868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pDzPRp</value>
      <webElementGuid>db8bdc3e-dcd2-46e5-b5eb-ebd4057e099f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0825416a-42a3-409f-b49c-6dee9bf99339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No. Handphone/Username/Email</value>
      <webElementGuid>e242cebc-3fdf-4d3e-8433-00d09eec4780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>5ac1381c-cb6b-45b3-a48c-81527307f40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loginKey</value>
      <webElementGuid>2d0d1d14-6941-43f2-b836-a2caffebe9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>2eca4810-8d42-4126-838f-e3662f2ccee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a5809917-f4b2-406c-8464-c6ac1317b3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>edca5a85-cc3a-48b6-b754-58b2006e7fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;vtexOX&quot;]/div[1]/div[@class=&quot;_3M9lzn PeA8Gc&quot;]/div[@class=&quot;Gxi65y&quot;]/div[2]/form[1]/div[@class=&quot;IxqCyD J1i6cp B-fiUo&quot;]/div[@class=&quot;yXry6s&quot;]/div[@class=&quot;D3QIf1&quot;]/div[@class=&quot;yup5K8 SdUtrz&quot;]/input[@class=&quot;pDzPRp&quot;]</value>
      <webElementGuid>ae8be942-1859-4f3b-b7a5-8e8d2dc87f51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='loginKey']</value>
      <webElementGuid>699fa1f8-480a-4399-ba46-03ac6a16031d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/div/div[2]/form/div/div[2]/div[2]/div/input</value>
      <webElementGuid>b5db4abc-f5c9-450b-9353-feea8fa1c29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c77f6b11-b989-4046-a388-d214f9a4589c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'No. Handphone/Username/Email' and @name = 'loginKey']</value>
      <webElementGuid>16b570ab-e96f-42cc-ac1e-64833bee537b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
